// <auto-generated />
using System;
using BeachRehberi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeachRehberi.API.Migrations
{
    [DbContext(typeof(BeachDbContext))]
    [Migration("20260320080644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BeachRehberi.API.Models.Beach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAccessibility")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAlcohol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDJ")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEntryFee")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasParking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRestaurant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasShower")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSunbeds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWaterSports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChildFriendly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupancyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccupancyPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SunbedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TodaySpecial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beaches");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Address = "Test",
                            CloseTime = "20:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Description = "API testi.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = false,
                            HasBar = false,
                            HasDJ = false,
                            HasEntryFee = false,
                            HasParking = false,
                            HasPool = false,
                            HasRestaurant = false,
                            HasShower = false,
                            HasSunbeds = false,
                            HasWaterSports = false,
                            HasWifi = false,
                            Instagram = "",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 20, 8, 6, 42, 879, DateTimeKind.Utc).AddTicks(9241),
                            Latitude = 36.869999999999997,
                            Longitude = 30.66,
                            Name = "TEST BEACH API",
                            OccupancyLevel = 1,
                            OccupancyPercent = 10,
                            OpenTime = "08:00",
                            Phone = "",
                            Rating = 5.0,
                            ReviewCount = 1,
                            SunbedPrice = 0m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 1,
                            Address = "Meltem, Beach Park No:10, Muratpaşa/Antalya",
                            CloseTime = "01:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Description = "Konyaaltı'nın en popüler beach club'larından.",
                            EntryFee = 0m,
                            GooglePlaceId = "ChIJeWMyN6yRwxQRGQAjkCC3kCs",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = true,
                            HasWifi = true,
                            Instagram = "@kalypsobeach",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 20, 8, 6, 42, 880, DateTimeKind.Utc).AddTicks(6770),
                            Latitude = 36.878581099999998,
                            Longitude = 30.665650200000002,
                            Name = "Kalypso Beach Club",
                            OccupancyLevel = 2,
                            OccupancyPercent = 60,
                            OpenTime = "08:30",
                            Phone = "+90 530 783 71 20",
                            Rating = 4.5999999999999996,
                            ReviewCount = 2741,
                            SunbedPrice = 400m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kuşkavağı, Akdeniz Blv. No:17, Konyaaltı/Antalya",
                            CloseTime = "23:59",
                            CoverImageUrl = "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800",
                            Description = "Gece gündüz açık, canlı müzikli plaj.",
                            EntryFee = 0m,
                            GooglePlaceId = "ChIJo0ibX0GRwxQRmp3ywLZoEtA",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "@sunshinebeachantalya",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 20, 8, 6, 42, 881, DateTimeKind.Utc).AddTicks(3775),
                            Latitude = 36.868841400000001,
                            Longitude = 30.649725499999999,
                            Name = "Sunshine Beach",
                            OccupancyLevel = 1,
                            OccupancyPercent = 45,
                            OpenTime = "00:00",
                            Phone = "+90 530 345 92 85",
                            Rating = 4.5999999999999996,
                            ReviewCount = 2814,
                            SunbedPrice = 300m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "Meltem, Akdeniz Blv. No:5, Muratpaşa/Antalya",
                            CloseTime = "01:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
                            Description = "Şık tasarım, premium hizmet.",
                            EntryFee = 0m,
                            GooglePlaceId = "ChIJjxyCDpWRwxQRkaHDzpSqOsM",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = true,
                            HasWifi = true,
                            Instagram = "@roxybeachantalya",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 20, 8, 6, 42, 881, DateTimeKind.Utc).AddTicks(3795),
                            Latitude = 36.881675399999999,
                            Longitude = 30.6724529,
                            Name = "Roxy Beach Lounge",
                            OccupancyLevel = 3,
                            OccupancyPercent = 80,
                            OpenTime = "08:00",
                            Phone = "+90 532 489 65 05",
                            Rating = 4.5,
                            ReviewCount = 2179,
                            SunbedPrice = 400m,
                            TodaySpecial = "",
                            Website = ""
                        });
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BeachEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSpots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAgeRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BeachPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCover")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BusinessUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("BusinessUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeachId = 1,
                            ContactName = "Kalypso Yönetici",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kalypso@beach.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$uO5ZQBzO5F9KN6sICQ42uO.cCu/eF/4E/RUu18f9TCY4qnzpuDqhG"
                        });
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SunbedCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BeachEvent", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany("Events")
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BeachPhoto", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany("Photos")
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BusinessUser", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany()
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Reservation", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany("Reservations")
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Review", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany("Reviews")
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Beach", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Photos");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
