// <auto-generated />
using System;
using BeachRehberi.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeachRehberi.API.Migrations
{
    [DbContext(typeof(BeachDbContext))]
    [Migration("20260321034558_AddNewBeaches")]
    partial class AddNewBeaches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BeachRehberi.API.Models.Beach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloseTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAccessibility")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAlcohol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDJ")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEntryFee")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasParking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRestaurant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasShower")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSunbeds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWaterSports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChildFriendly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupancyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccupancyPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SunbedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TodaySpecial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beaches");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Address = "Test",
                            CloseTime = "20:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Description = "API testi.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = false,
                            HasBar = false,
                            HasDJ = false,
                            HasEntryFee = false,
                            HasParking = false,
                            HasPool = false,
                            HasRestaurant = false,
                            HasShower = false,
                            HasSunbeds = false,
                            HasWaterSports = false,
                            HasWifi = false,
                            Instagram = "",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 964, DateTimeKind.Utc).AddTicks(1222),
                            Latitude = 36.869999999999997,
                            Longitude = 30.66,
                            Name = "TEST BEACH API",
                            OccupancyLevel = 1,
                            OccupancyPercent = 10,
                            OpenTime = "08:00",
                            Phone = "",
                            Rating = 5.0,
                            ReviewCount = 1,
                            SunbedPrice = 0m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 1,
                            Address = "Meltem, Beach Park No:10, Muratpaşa/Antalya",
                            CloseTime = "01:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Description = "Konyaaltı'nın en popüler beach club'larından.",
                            EntryFee = 0m,
                            GooglePlaceId = "ChIJeWMyN6yRwxQRGQAjkCC3kCs",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = true,
                            HasWifi = true,
                            Instagram = "@kalypsobeach",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 964, DateTimeKind.Utc).AddTicks(6984),
                            Latitude = 36.878581099999998,
                            Longitude = 30.665650200000002,
                            Name = "Kalypso Beach Club",
                            OccupancyLevel = 2,
                            OccupancyPercent = 60,
                            OpenTime = "08:30",
                            Phone = "+90 530 783 71 20",
                            Rating = 4.5999999999999996,
                            ReviewCount = 2741,
                            SunbedPrice = 400m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kuşkavağı, Akdeniz Blv. No:17, Konyaaltı/Antalya",
                            CloseTime = "23:59",
                            CoverImageUrl = "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800",
                            Description = "Gece gündüz açık, canlı müzikli plaj.",
                            EntryFee = 0m,
                            GooglePlaceId = "ChIJo0ibX0GRwxQRmp3ywLZoEtA",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "@sunshinebeachantalya",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1420),
                            Latitude = 36.868841400000001,
                            Longitude = 30.649725499999999,
                            Name = "Sunshine Beach",
                            OccupancyLevel = 1,
                            OccupancyPercent = 45,
                            OpenTime = "00:00",
                            Phone = "+90 530 345 92 85",
                            Rating = 4.5999999999999996,
                            ReviewCount = 2814,
                            SunbedPrice = 300m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "Meltem, Akdeniz Blv. No:5, Muratpaşa/Antalya",
                            CloseTime = "01:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
                            Description = "Şık tasarım, premium hizmet.",
                            EntryFee = 0m,
                            GooglePlaceId = "ChIJjxyCDpWRwxQRkaHDzpSqOsM",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = true,
                            HasWifi = true,
                            Instagram = "@roxybeachantalya",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1589),
                            Latitude = 36.881675399999999,
                            Longitude = 30.6724529,
                            Name = "Roxy Beach Lounge",
                            OccupancyLevel = 3,
                            OccupancyPercent = 80,
                            OpenTime = "08:00",
                            Phone = "+90 532 489 65 05",
                            Rating = 4.5,
                            ReviewCount = 2179,
                            SunbedPrice = 400m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 5,
                            Address = "Sahil Yaşam Parkı No:7, Konyaaltı/Antalya",
                            CloseTime = "02:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Description = "Canlı müzik ve kokteyllerle sahil keyfi.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1614),
                            Latitude = 36.880509600000003,
                            Longitude = 30.6699175,
                            Name = "Flamingo Lounge",
                            OccupancyLevel = 2,
                            OccupancyPercent = 50,
                            OpenTime = "09:00",
                            Phone = "+90 555 053 13 36",
                            Rating = 4.2000000000000002,
                            ReviewCount = 850,
                            SunbedPrice = 200m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 6,
                            Address = "Konyaaltı Beachpark, Konyaaltı/Antalya",
                            CloseTime = "20:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800",
                            Description = "1999'dan beri Konyaaltı'nın köklü plajlarından, aile dostu.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = false,
                            HasBar = true,
                            HasDJ = false,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = true,
                            HasWifi = false,
                            Instagram = "",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1621),
                            Latitude = 36.875,
                            Longitude = 30.658000000000001,
                            Name = "Aydın Beach Club",
                            OccupancyLevel = 1,
                            OccupancyPercent = 40,
                            OpenTime = "08:00",
                            Phone = "",
                            Rating = 4.5,
                            ReviewCount = 1200,
                            SunbedPrice = 150m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 7,
                            Address = "Arapsuyu, Akdeniz Bulv. No:64, Konyaaltı/Antalya",
                            CloseTime = "19:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
                            Description = "Burger, pizza ve frozen içeceklerle sahil keyfi.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = false,
                            HasBar = true,
                            HasDJ = false,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = false,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = false,
                            Instagram = "",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1624),
                            Latitude = 36.868099999999998,
                            Longitude = 30.649799999999999,
                            Name = "Lucky 13 Beach Restaurant",
                            OccupancyLevel = 1,
                            OccupancyPercent = 30,
                            OpenTime = "08:00",
                            Phone = "0542 408 07 87",
                            Rating = 4.0,
                            ReviewCount = 430,
                            SunbedPrice = 100m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 8,
                            Address = "Akdeniz Bulvarı No:15, Konyaaltı/Antalya",
                            CloseTime = "01:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Description = "Canlı müzik ve deniz ürünleriyle gece hayatı.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1628),
                            Latitude = 36.880000000000003,
                            Longitude = 30.664999999999999,
                            Name = "Ferma Beach",
                            OccupancyLevel = 2,
                            OccupancyPercent = 55,
                            OpenTime = "12:00",
                            Phone = "",
                            Rating = 4.0999999999999996,
                            ReviewCount = 620,
                            SunbedPrice = 250m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 9,
                            Address = "Kuşkavağı Mah., Akdeniz Bulv. No:25/1, Konyaaltı/Antalya",
                            CloseTime = "02:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800",
                            Description = "Sunset manzarasıyla bistro yemekleri ve şezlong keyfi.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1646),
                            Latitude = 36.866022299999997,
                            Longitude = 30.645267799999999,
                            Name = "Twenty Beach & Bistro",
                            OccupancyLevel = 1,
                            OccupancyPercent = 45,
                            OpenTime = "11:00",
                            Phone = "",
                            Rating = 4.5,
                            ReviewCount = 980,
                            SunbedPrice = 200m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 10,
                            Address = "Kuşkavağı Mah., Akdeniz Bulv. No:27/21, Konyaaltı/Antalya",
                            CloseTime = "01:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
                            Description = "Kahvaltıdan geceye kadar sahil keyfi, aile dostu.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1649),
                            Latitude = 36.866999999999997,
                            Longitude = 30.646000000000001,
                            Name = "Alabama Beach & Restaurant",
                            OccupancyLevel = 2,
                            OccupancyPercent = 50,
                            OpenTime = "09:00",
                            Phone = "",
                            Rating = 4.5,
                            ReviewCount = 750,
                            SunbedPrice = 200m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 11,
                            Address = "Akdeniz Blv. No:22, Kuşkavağı, Konyaaltı/Antalya",
                            CloseTime = "02:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Description = "Bohemian atmosfer, steakhouse ve DJ performance.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1654),
                            Latitude = 36.866999999999997,
                            Longitude = 30.648,
                            Name = "La Bohem Beach Restaurant",
                            OccupancyLevel = 3,
                            OccupancyPercent = 70,
                            OpenTime = "12:00",
                            Phone = "+90 540 156 07 56",
                            Rating = 4.5999999999999996,
                            ReviewCount = 1100,
                            SunbedPrice = 500m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 12,
                            Address = "Akdeniz Blv. No:33, Konyaaltı/Antalya",
                            CloseTime = "02:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800",
                            Description = "Premium şezlong ve daybed, steakhouse ve gece müziği.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1657),
                            Latitude = 36.862472799999999,
                            Longitude = 30.639734300000001,
                            Name = "Dubai Beach Konyaaltı",
                            OccupancyLevel = 2,
                            OccupancyPercent = 65,
                            OpenTime = "09:00",
                            Phone = "+90 537 652 25 94",
                            Rating = 4.5999999999999996,
                            ReviewCount = 1850,
                            SunbedPrice = 400m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 13,
                            Address = "Akdeniz Bulvarı, Konyaaltı/Antalya",
                            CloseTime = "23:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
                            Description = "Kahve ve sahil keyfinin buluştuğu sakin atmosfer.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = false,
                            HasBar = true,
                            HasDJ = false,
                            HasEntryFee = false,
                            HasParking = false,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = false,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1661),
                            Latitude = 36.878999999999998,
                            Longitude = 30.661999999999999,
                            Name = "Vento Mare Coffee & Beach",
                            OccupancyLevel = 1,
                            OccupancyPercent = 30,
                            OpenTime = "09:00",
                            Phone = "",
                            Rating = 4.2999999999999998,
                            ReviewCount = 320,
                            SunbedPrice = 150m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 14,
                            Address = "Gürsu Mah. Akdeniz Blv. No:45/1, Konyaaltı/Antalya",
                            CloseTime = "02:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Description = "Akdeniz mutfağı, kokteyl ve her gece DJ performance.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1664),
                            Latitude = 36.8795,
                            Longitude = 30.663499999999999,
                            Name = "Cafe Belle Bistro & Beach",
                            OccupancyLevel = 2,
                            OccupancyPercent = 55,
                            OpenTime = "09:00",
                            Phone = "",
                            Rating = 4.5,
                            ReviewCount = 680,
                            SunbedPrice = 300m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 15,
                            Address = "Gürsu Mah. Akdeniz Blv., Konyaaltı/Antalya",
                            CloseTime = "01:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800",
                            Description = "Pizza, burger ve daybed ile bohem sahil atmosferi.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = false,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = false,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1680),
                            Latitude = 36.880000000000003,
                            Longitude = 30.664000000000001,
                            Name = "Kuki Box Beach Lounge",
                            OccupancyLevel = 2,
                            OccupancyPercent = 60,
                            OpenTime = "10:00",
                            Phone = "+90 242 248 47 07",
                            Rating = 4.4000000000000004,
                            ReviewCount = 540,
                            SunbedPrice = 400m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 16,
                            Address = "Gürsu Mah. Akdeniz Bulvarı, Konyaaltı/Antalya",
                            CloseTime = "23:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
                            Description = "Aile dostu, oyun parkı ve kahvaltıyla sahil keyfi.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = true,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = false,
                            Instagram = "",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1684),
                            Latitude = 36.879199999999997,
                            Longitude = 30.662800000000001,
                            Name = "Frida Beach 33",
                            OccupancyLevel = 1,
                            OccupancyPercent = 35,
                            OpenTime = "08:00",
                            Phone = "+90 530 668 21 07",
                            Rating = 4.0,
                            ReviewCount = 290,
                            SunbedPrice = 150m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 17,
                            Address = "Liman Mah. Akdeniz Blv. No:207, Konyaaltı/Antalya",
                            CloseTime = "23:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
                            Description = "Pet friendly, bistro yemekleri ve aile dostu sahil.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = false,
                            HasBar = true,
                            HasDJ = false,
                            HasEntryFee = false,
                            HasParking = false,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1687),
                            Latitude = 36.881999999999998,
                            Longitude = 30.672999999999998,
                            Name = "Shakespeare Beach",
                            OccupancyLevel = 1,
                            OccupancyPercent = 40,
                            OpenTime = "08:00",
                            Phone = "+90 507 072 06 00",
                            Rating = 4.2000000000000002,
                            ReviewCount = 410,
                            SunbedPrice = 200m,
                            TodaySpecial = "",
                            Website = ""
                        },
                        new
                        {
                            Id = 18,
                            Address = "Akdeniz Blv. No:211, Liman, Konyaaltı/Antalya",
                            CloseTime = "23:00",
                            CoverImageUrl = "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800",
                            Description = "Sakin atmosfer, deniz manzarası ve özenli servis.",
                            EntryFee = 0m,
                            GooglePlaceId = "",
                            HasAccessibility = false,
                            HasAlcohol = true,
                            HasBar = true,
                            HasDJ = true,
                            HasEntryFee = false,
                            HasParking = false,
                            HasPool = false,
                            HasRestaurant = true,
                            HasShower = true,
                            HasSunbeds = true,
                            HasWaterSports = false,
                            HasWifi = true,
                            Instagram = "",
                            IsChildFriendly = true,
                            IsOpen = true,
                            LastUpdated = new DateTime(2026, 3, 21, 3, 45, 57, 965, DateTimeKind.Utc).AddTicks(1691),
                            Latitude = 36.882199999999997,
                            Longitude = 30.673500000000001,
                            Name = "Riviera Beach Lounge",
                            OccupancyLevel = 1,
                            OccupancyPercent = 30,
                            OpenTime = "09:00",
                            Phone = "",
                            Rating = 4.7999999999999998,
                            ReviewCount = 95,
                            SunbedPrice = 300m,
                            TodaySpecial = "",
                            Website = ""
                        });
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BeachEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableSpots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAgeRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BeachPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCover")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BusinessUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("BusinessUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeachId = 1,
                            ContactName = "Kalypso Yönetici",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kalypso@beach.com",
                            IsActive = true,
                            PasswordHash = "UOm0YNf5xsCBeKQJM3Yxt8d8zNcBESfLxj3H1gKKQbE="
                        });
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SunbedCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeachId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BeachEvent", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany("Events")
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BeachPhoto", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany("Photos")
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.BusinessUser", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany()
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Reservation", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany("Reservations")
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Review", b =>
                {
                    b.HasOne("BeachRehberi.API.Models.Beach", "Beach")
                        .WithMany("Reviews")
                        .HasForeignKey("BeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beach");
                });

            modelBuilder.Entity("BeachRehberi.API.Models.Beach", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Photos");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
